name: Streamlit app

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  streamlit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      working-directory: components/chart
      run: npm install

    - name: Build the frontend project
      working-directory: components/chart
      run: npm run build

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.11'
          
    - name: Deploy streamlit app
      uses: streamlit/streamlit-app-action@v0.0.3
      with:
        app-path: streamlit_app.py
        ruff: true